name: .NET Core Desktop

on:
  push:
    branches: [ main, developer ]

jobs:
  test_job:
    name: Executando o Job de Teste
    runs-on: ubuntu-latest
    steps:
    - name: Step 1
      uses: actions/checkout@v2

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: 'mayasilva'
        password: ${{ secrets.DOCKERHUB_PASS}}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.7.0
      with:
        context: .
        tags: 'mayasilva/githubaction-fiap:latest'
        push: true
        

