name: .NET Core Desktop

on:
  push:
    branches: [ "main", "developer" ]

jobs:
  test_job:
    name: Executando o Job de Teste
    runs-on: ubuntu-hosted
    steps:
    - name: Step 1
      uses: actions/checkout@v2

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        # Username used to log against the Docker registry
        username: 'mayasilva'
        password: ${{ secrets.DOCKERHUB_PASS}}
